steps:
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s-config-file.yaml
    - --image=gcr.io/western-antonym-322000/productservice:1.0
    - --location=us-central1-a
    - --cluster=standard-cluster-1