steps:
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s-config-file.yaml
    - --image=gcr.io/gcp-demo-277801/productservice:1.0
    - --location=us-east1-b
    - --cluster=cluster-1