steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
    # build/push the container image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/cicd-284616/productservice:1.0", "--build-arg=JAR_FILE=target/productservice-0.0.1-SNAPSHOT.jar", "."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/cicd-284616/productservice:1.0"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s-config-file.yaml
    - --image=gcr.io/cicd-284616/productservice:1.0
    - --location=us-west1-a
    - --cluster=cluster-1
