steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/cicd-284616/productservice:1.0", "--build-arg=JAR_FILE=target/*.jar", "."]
images: ["gcr.io/cicd-284616/productservice"]