kind: Deployment
apiVersion: apps/v1
metadata:
  name: productservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: jiayinzhuo/productservice
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: productservice
  labels:
    app: productservice
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31819
  selector:
    app: productservice