apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  selector:
    matchLabels:
      app: productservice
  replicas: 1
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: jiayinzhuo/productservice:latest
          ports:
            - containerPort: 8080   
---
apiVersion: v1
kind: Service
metadata:
  name: productservice-service
spec:
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  